// Data js

const data={
    smoothie_playlist: [
        // 🔹 CHALISA Songs
        {
            id: 1,
            thumbnail: "/images/hanuman-chalisa.jpg",
            title: "Hanuman Chalisa",
            desc: "Glory to Lord Hanuman",
            type: "CHALISA",
            author: "T Series",
            duration: "9:43",
            src: "/songs/song1.mp3",
        },
        {
            id: 2,
            thumbnail: "/images/shiv-chalisa.jpg",
            title: "Shiv Chalisa",
            desc: "Glory to Lord Shiv",
            type: "CHALISA",
            author: "T Series",
            duration: "9:43",
            src: "/songs/song2.mp3",
        },
        {
            id: 3,
            thumbnail: "/images/durga-chalisa.jpg",
            title: "Durga Chalisa",
            desc: "Glory to Maa Durga",
            type: "CHALISA",
            author: "T Series",
            duration: "9:43",
            src: "/songs/song3.mp3",
        },
        {
            id: 4,
            thumbnail: "/images/ganesh-chalisa.jpg",
            title: "Ganesh Chalisa",
            desc: "Glory to Lord Ganesh",
            type: "CHALISA",
            author: "T Series",
            duration: "9:43",
            src: "/songs/song4.mp3",
        },
        {
            id: 5,
            thumbnail: "/images/krishna-chalisa.jpg",
            title: "Krishna Chalisa",
            desc: "Glory to Lord Krishna",
            type: "CHALISA",
            author: "T Series",
            duration: "9:43",
            src: "/songs/song1.mp3",
        },
    
        // 🔹 BHAJAN Songs
        {
            id: 6,
            thumbnail: "/images/mithe-ras.jpg",
            title: "Radha Rani Bhajan",
            type: "BHAJAN",
            about: "RADHA-RANI",
            desc: "Mithe Ras se Bharyori Radha Rani",
            author: "Jaya Kishori",
            duration: "4:42",
            src: "/songs/song2.mp3",
        },
        {
            id: 7,
            thumbnail: "/images/shyam-bhajan.jpg",
            title: "Shyam Bhajan",
            type: "BHAJAN",
            desc: "Devotional Bhajan for Lord Krishna",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song5.mp3",
        },
        {
            id: 8,
            thumbnail: "/images/shiv-bhajan.jpg",
            title: "Shiv Bhajan",
            type: "BHAJAN",
            desc: "Bhajan dedicated to Lord Shiva",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song3.mp3",
        },
        {
            id: 9,
            thumbnail: "/images/ram-bhajan.jpg",
            title: "Ram Bhajan",
            type: "BHAJAN",
            desc: "Praise and devotion for Lord Ram",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song4.mp3",
        },
        {
            id: 10,
            thumbnail: "/images/durga-bhajan.jpg",
            title: "Durga Bhajan",
            type: "BHAJAN",
            desc: "Devotional song for Maa Durga",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song1.mp3",
        },
    
        // 🔹 SPIRITUAL-SONG
        {
            id: 11,
            thumbnail: "/images/song1.jpg",
            title: "Adhuram Maduram",
            type: "SPIRITUAL-SONG",
            desc: "Divine & Holy Krishna Song.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song2.mp3",
        },
        {
            id: 12,
            thumbnail: "/images/song2.jpg",
            title: "Mujhe Ras Aa Gya Hai",
            type: "SPIRITUAL-SONG",
            desc: "Soulful chants and divine music.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song5.mp3",
        },
        {
            id: 13,
            thumbnail: "/images/song3.jpg",
            title: "Main Balak, Tu Mata",
            type: "SPIRITUAL-SONG",
            desc: "Divine & Holy Maa Durga Song.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song4.mp3",
        },
        {
            id: 14,
            thumbnail: "/images/song4.jpg",
            title: "Bhola Hai Bhandari",
            type: "SPIRITUAL-SONG",
            desc: "Spiritual music that touches the soul.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song2.mp3",
        },
        {
            id: 15,
            thumbnail: "/images/song5.jpg",
            title: "Sufi Sangeet",
            type: "SPIRITUAL-SONG",
            desc: "Mystical and spiritual sufi songs.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song1.mp3",
        },
    
        // 🔹 SPIRITUAL-PODCAST
        {
            id: 16,
            thumbnail: "/images/bhagwat-katha.jpg",
            title: "Bhagwat Katha",
            type: "SPIRITUAL-PODCAST",
            desc: "Shrimad Bhagwat Maha Puran.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song2.mp3",
        },
        {
            id: 12,
            thumbnail: "/images/shiv-mahapuran.jpg",
            title: "Shiv Maha Puran",
            type: "SPIRITUAL-PODCAST",
            desc: "Soulful chants and divine shiv mahapuran.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song4.mp3",
        },
        {
            id: 18,
            thumbnail: "/images/podcast1.jpg",
            title: "Vedic Wisdom",
            type: "SPIRITUAL-PODCAST",
            desc: "Insights from ancient Vedic scriptures.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song1.mp3",
        },
        {
            id: 19,
            thumbnail: "/images/bhagavad-gita.jpg",
            title: "Bhagavad Gita Teachings",
            type: "SPIRITUAL-PODCAST",
            desc: "Teachings from the Bhagavad Gita.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song5.mp3",
        },
        {
            id: 20,
            thumbnail: "/images/spiritual-awakening.jpg",
            title: "Spiritual Awakening",
            type: "SPIRITUAL-PODCAST",
            desc: "Deep conversations on spirituality.",
            author: "Unknown Artist",
            duration: "3:42",
            src: "/songs/song3.mp3",
        },
    ],
    search_result_category: [
        "All",
        "Songs",
        "Artists",
        "Playlist",
        "Albums",
        "Podcasts & Shows",
        "Profiles",

    ],
};

export default data;